### ISSUE TITLE
Prepare HM for CC-1.15.1 

### ISSUE THREAD

**Issue by Whitecat106** [Whitecat106/Historic-Missions#15]
Need to: 
- Add descriptions for contract entities
- Rename contract agencies 
- Sort agencies into efficient groups 
- Work out a way to define agencies in chronological order? 
  Maybe @jrossignol could point me in the right direction please? My question is basically would it be possible to add an index to contract groups to force them to appear in the Mission control in a particular order? I understand that by using a date range as the Contract Group name attribute the effect would be similar but would be problematic for multi era programs such as the space shuttle. 
- Add in some fixes, such as Soyuz-T-6, Gemini ATV's etc...

**Comment by jrossignol** [comment]
My plan was to add a sortKey field for CONTRACT_TYPE to allow spring within a group.  I can do the same for v CONTRACT_GROUP, with the caveat that it would only work for child groups.  The reasoning is I don't want one contract pack to do stuff that can affect others (such as using the sort order to force itself to the top of the list).

So for you I'd suggest something like:
Historic Missions
|- Gemini
|- Apollo
Etc.

The other thing that I forgot about was the intermediate groups that you use for setting maxSimultaneous for a subset of contracts.  Do you still need this functionality?  If so I'll need to introduce functionality to hide these nodes in the hierarchy.

I'll try to get these changes done tonight.

**Comment by Whitecat106** [comment]
I see your reasoning! However within child groups would work too, since my pack is defined from the HistoricMissions group with a max simultaneous of 100 and then by say 'apollo group', 'gemini group'.

 This would allow a chronological order for subgroups along with alphabetical order for the actual contract pack with other packs in the mission control preventing packs from bumping themselves to the top! :) 

I do not actually use max simultaneous too much, it's only really necessary for afew contracts (since I have added the newVessel requirement) such as the buran shuttle mission and the space shuttle, both have similar requirements that would fulfil eachother so they needed to be separated, the same with some early apollo and Soyuz missions. 

I love the new changes, really makes the mission control more friendly and organised!
